services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: news-hub
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - app

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "5000:80"
    networks:
      - app
    volumes:
      - db_data:/var/lib/mysql

networks:
  app:
    driver: bridge
volumes:
  db_data: